language: java

jdk:
  - openjdk8

sudo: false

install: ./mvnw dependency:list -Dsort -B -U -V

script:
  - ./mvnw verify -Pci -B -U
  - ./mvnw verify -Pjqa -B -U

cache:
  directories:
    - $HOME/.m2

